GET http://localhost:3001/api/blogs

###
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title":"testing",
    "url":"http://nepal.com",
    "author":"yrlo",
    "likes":2
}

###
DELETE http://localhost:3001/api/blogs/5

###
PUT http://localhost:3001/api/blogs/4
Content-Type: application/json

{
   "title": "checking Connection",
    "url": "http://nepal.com",
    "author": "baas",
    "likes": 5
}